<?php
namespace Tk\Db;

use Tk\DataMap\Db\DateTime;
use Tk\Money;
use Tk\ObjectUtil;
use Tk\Traits\DataTrait;
use Tk\DataMap\DataMap;
use Tk\Db;

/**
 * Abstract class for Models that serves as the base to handle mappings, queries, and interactions
 * with the database. This class offers default behavior for common operations such as finding,
 * retrieving, and mapping database rows to objects.
 *
 * When implementing your own Models, constructors cannot have any required params.
 * <?php
 *      // OK
 *      public function __construct(int $testId = 0)
 *      {
 *          $this->testId = $testId;
 *      }
 *
 *      // ERROR
 *      public function __construct(int $testId)
 *      {
 *          $this->testId = $testId;
 *      }
 *
 *      // Use a factory method in favor of required constructor params
 *      public static function create(int $testId): self
 *      {
 *          $obj = new self();
 *          $obj->testId = $testId;
 *          return $obj;
 *      }
 * ?>
 *
 */
abstract class Model
{
    use DataTrait;

    /**
     * Class datamaps, by default, each class has a single DataMap
     * generated by the getDataMap function
     * @var DataMap[]|array
     */
    protected static array $_MAPS = [];

    const array FORCE_READ_ONLY = ['modified', 'created'];

    /**
     * Leave this empty if you want to use the default table/view
     * Default table/view name is the snake name of the class CamelCase name
     * @see static::getPrimaryTable()
     */
    const string DB_TABLE  = '';

    /**
     * default find query
     */
    public static function find(int $id): ?static
    {
        $table = static::getPrimaryTable();
        $column = static::getPrimaryColumn();
        return Db::queryOne("
            SELECT *
            FROM {$table}
            WHERE {$column} = :id",
            compact('id'),
            static::class
        );
    }

    /**
     * default must find
     * throws exception on failure to find row
     */
    public static function mustFind(int $id): static
    {
        $table = static::getPrimaryTable();
        $column = static::getPrimaryColumn();
        $obj = Db::queryOne("
            SELECT *
            FROM {$table}
            WHERE {$column} = :id",
            compact('id'),
            static::class
        );
        if (!($obj instanceof static)) {
            throw new \Tk\Exception(static::class . " not found with id {$id}");
        }
        return $obj;
    }

    /**
     * default find all
     * @return array<int,static>
     */
    public static function findAll(): array
    {
        $table = static::getPrimaryTable();
        return Db::query("
            SELECT *
            FROM {$table}",
            [],
            static::class
        );
    }

    /**
     * Used by the \Tk\Db object to map a row to an object
     */
    public function __map(array $row, ?DataMap $map = null): void
    {
        Db::$LOG = false;
        if (is_null($map)) {
            $map = static::getDataMap();
        }
        $map->loadObject($this, $row);
        Db::$LOG = true;
    }

    /**
     * map form values array to object properties
     */
    public function mapForm(array $values): static
    {
        $map = static::getFormMap();
        $map->loadObject($this, $values);
        return $this;
    }

    /**
     * map object properties to form values array
     */
    public function unmapForm(): array
    {
        $map = static::getFormMap();
        $values = [];
        $map->loadArray($values, $this);
        return $values;
    }

	/**
	 * load properties of this object from the database
	 */
    public function reload(): void
    {
        Db::$LOG = false;
        $map = static::getDataMap();
        $priKey = $map->getPrimaryKey()?->getProperty();
        if (is_null($priKey)) {
            Db::$LOG = true;
            return;
        }
        $id = $this->$priKey;

        if ($id) {
            $obj = static::find($id);
        } else {
            $rc = new \ReflectionClass(static::class);
            $obj = $rc->newInstanceWithoutConstructor();
        }
        if (is_null($obj)) {
            Db::$LOG = true;
            return;
        }
		foreach (get_object_vars($obj) as $prop => $val) {
			$this->$prop = $val;
		}
        Db::$LOG = true;
    }

    /**
     * Return the primary int id of a model
     * Does not support models with a non-integer ID type
     */
    public function getId(): int
    {
        $priKey = static::getPrimaryProperty();
        if (empty($priKey) || !is_numeric($this->$priKey)) return 0;
        return intval($this->$priKey);
    }

    public static function getPrimaryProperty(): string
    {
        return static::getDataMap()->getPrimaryKey()?->getProperty() ?? '';
    }

    public static function getPrimaryColumn(): string
    {
        return static::getDataMap()->getPrimaryKey()?->getColumn() ?? '';
    }

    /**
     * return a table or view that is used as the primary lookup table
     * If using a non-standard table/view define DB_TABLE in your Model object
     */
    public static function getPrimaryTable(): string
    {
        if (!empty(static::DB_TABLE)) return static::DB_TABLE;
        $view = static::getDbView();
        if ($view) return $view;
        return static::getDbTable();
    }

    /**
     * return a snake style DB table name generated from the class name
     */
    public static function getDbTable(): string
    {
        return strtolower(preg_replace('/(?<!^)[A-Z]+|(?<!^|\d)[\d]+/', '_$0', strval(ObjectUtil::basename(static::class))));
    }

    /**
     * return the DB view name if exists returns empty string if not
     * All views are assumed to be the default table name with 'v_' prepended
     */
    public static function getDbView(): string
    {
        $table = static::getDbTable();
        $view = "v_{$table}";
        if (Db::tableExists($view)) return $view;
        return '';
    }

    /**
     * Auto generate a DataMap for this object.
     *
     * Default table name is the snake case of the class name, 'MenuItem' => 'menu_item'
     * Default view name is the same with 'v_' prepended, 'v_menu_item'
     * If the view table does not exist, it is ignored
     *
     * Override this method if you need to create a custom DataMap with different table names
     */
    public static function getDataMap(): DataMap
    {
        $name = static::class;
        if (static::hasMap($name)) {
            return static::getMap($name);
        }
        Db::$LOG = false;

        // autogen table/view name from class
        $table = static::getDbTable();
        $view = static::getDbView();
        if (empty($view)) $view = $table;

        $v_meta = [];
        $t_meta = Db::getTableInfo($table);
        if (!empty($view)) {
            $v_meta = Db::getTableInfo($view);
        }

        Db::$LOG = true;

        $roCols = array_diff_key($v_meta, $t_meta);
        $map = new DataMap();

        // autogenerate a data map from DB and object metadata
        foreach ($t_meta+$roCols as $meta) {
            if (!property_exists($name, $meta->name_camel)) continue;
            $prop = new \ReflectionProperty(static::class, $meta->name_camel);

            $typeName = '';
            if ($prop->getType() instanceof \ReflectionNamedType) {
                $typeName = $prop->getType()->getName();
            }

            if ($typeName == Money::class) {
                $meta->php_type = $typeName;
            }
            if ($typeName == 'stdClass') {
                $meta->php_type = 'json';
            }
            if ($typeName == 'array') {
                $meta->php_type = 'array';
            }

            $type = DataMap::makeDbType($meta);
            $type->setNullable($prop->getType()->allowsNull());

            if ($meta->is_primary_key) {
                $type->setFlag(DataMap::PRI);
            }

            if (
                $meta->Extra == 'VIRTUAL GENERATED' ||              // virtual field
                $prop->isReadOnly() ||                              // prop is readonly
                ($roCols[$meta->name] ?? false) ||                  // col not in table
                in_array($meta->name_camel, self::FORCE_READ_ONLY)  // tk system readonly props
            ) {
                $type->setAccess(DataMap::READ);
            }

            if ($type instanceof DateTime && $typeName == 'DateTimeImmutable') {
                $type->setImmutable(true);
            }

            $map->addType($type);
        }

        static::setMap($name, $map);
        return $map;
    }

    public static function getFormMap(): DataMap
    {
        $name = 'form_'. static::class;
        if (static::hasMap($name)) return static::getMap($name);

        Db::$LOG = false;

        $map = new DataMap();
        $primaryId = static::getDataMap()->getPrimaryKey()->getProperty();

        $reflect = new \ReflectionClass(static::class);
        $props = $reflect->getProperties(\ReflectionProperty::IS_PUBLIC | \ReflectionProperty::IS_PROTECTED);
        foreach ($props as $prop) {
            if (str_starts_with($prop->getName(), '_') || $prop->isStatic()) continue;

            $typeName = '';
            if ($prop->getType() instanceof \ReflectionNamedType) {
                $typeName = $prop->getType()->getName();
            }

            // ignored types
            if (in_array($typeName, ['stdClass'])) continue;

            $type = DataMap::makeFormType($typeName, $prop->getName());
            $type->setNullable($prop->getType()->allowsNull());

            if ($primaryId == $prop->getName()) {
                $type->setFlag(DataMap::PRI);
            }

            if (
                $prop->isReadOnly() ||
                in_array($prop->getName(), self::FORCE_READ_ONLY)
            ) {
                $type->setAccess(DataMap::READ);
            }

            $map->addType($type);
        }
        static::setMap($name, $map);

        Db::$LOG = true;

        return $map;
    }

    public static function getMap(string $name): ?DataMap
    {
        return self::$_MAPS[$name] ?? null;
    }

    public static function setMap(string $name, DataMap $map): void
    {
        self::$_MAPS[$name] = $map;
    }

    public static function hasMap(string $name): bool
    {
        return array_key_exists($name, self::$_MAPS);
    }

    /**
     * return a file data path for this object
     */
    public function getDataPath(): string
    {
        if (property_exists($this, 'dataPath')) {
            return $this->dataPath;
        }
        return '';
    }

}