<?php
namespace Tk\Db;

use Tk\Config;
use Tk\DataMap\Db\DateTime;
use Tk\Money;
use Tk\ObjectUtil;
use Tk\Traits\DataTrait;
use Tk\DataMap\DataMap;
use Tk\Db;

abstract class Model
{
    use DataTrait;

    /**
     * Class datamaps, by default each class has a single DataMap
     * generated by the getDataMap function
     * @var DataMap[]|array
     */
    protected static array $_MAPS = [];

    const array FORCE_READ_ONLY = ['modified', 'created'];

    /**
     * method trys to return an object from the fkey, fid values
     * if no fkey is used the calling classname is used
     */
    public static function findDbModel(int $fid, ?string $fkey = null): ?static
    {
        if (is_null($fkey)) $fkey = static::class;
        if ($fkey == self::class || !class_exists($fkey)) {
            throw new \Tk\Exception("Invalid model class");
        }
        if (method_exists($fkey, 'find')) {
            return $fkey::find($fid);
        }
        return null;
    }

    /**
     * Magic method to map an array to an object using the dataMap
     */
    public function __map(array $row, ?DataMap $map = null): void
    {
        Db::$LOG = false;
        if (is_null($map)) {
            $map = static::getDataMap();
        }
        $map->loadObject($this, $row);
        Db::$LOG = true;
    }

    /**
     * map an array of values to an object using the form data map
     */
    public function mapForm(array $values): static
    {
        $map = static::getFormMap();
        $map->loadObject($this, $values);
        return $this;
    }

    /**
     * map this objects values to an array using the from data map
     */
    public function unmapForm(): array
    {
        $map = static::getFormMap();
        $values = [];
        $map->loadArray($values, $this);
        return $values;
    }

	/**
	 * load properties of this object from database
	 */
    public function reload(): void
    {
        Db::$LOG = false;
        $map = static::getDataMap();
        $priKey = $map->getPrimaryKey()?->getProperty();
        if (is_null($priKey)) {
            Db::$LOG = true;
            return;
        }
        $id = $this->$priKey;

        if ($id && method_exists($this, 'find')) {
            /** @phpstan-ignore-next-line */
            $obj = static::find($id);
        } else {
            // TODO: this could be a potential issue if the constructor requires params
            /** @phpstan-ignore-next-line */
            $obj = new static();
        }
        if (is_null($obj)) {
            Db::$LOG = true;
            return;
        }
		foreach (get_object_vars($obj) as $prop => $val) {
			$this->$prop = $val;
		}
        Db::$LOG = true;
    }

    /**
     * Return the primary int id of a model
     * Does not support models with a non integer ID type
     */
    public function getId(): int
    {
        $priKey = static::getPrimaryProperty();
        if (empty($priKey)) return 0;
        return intval($this->$priKey ?? 0);
    }

    /**
     * @deprecated use getPrimaryProperty()
     */
    public function getPrimaryKey(): string
    {
        return static::getPrimaryProperty();
    }

    public static function getPrimaryProperty(): string
    {
        return static::getDataMap()->getPrimaryKey()?->getProperty() ?? '';
    }

    public static function getPrimaryColumn(): string
    {
        return static::getDataMap()->getPrimaryKey()?->getColumn() ?? '';
    }

    /**
     * return the DB table name for this object
     */
    public static function getDbTable(): string
    {
        return strtolower(preg_replace('/(?<!^)[A-Z]+|(?<!^|\d)[\d]+/', '_$0', strval(ObjectUtil::basename(static::class))));
    }

    /**
     * return the DB view name it exists, empty if not
     */
    public static function getDbView(): string
    {
        $table = static::getDbTable();
        $view = "v_{$table}";
        if (Db::tableExists($view)) return $view;
        return '';
    }

    /**
     * Auto generate a DataMap for this object.
     *
     * Default table name is the snake case of the class name, 'MenuItem' => 'menu_item'
     * Default view name is the same with 'v_' prepended, ''v_menu_item'
     * If the view table does not exist it is ignored
     *
     * Override this method if you need to create a custom DataMap with different table names
     *
     * @note Remember to check your queries are using the view if required.
     */
    public static function getDataMap(): DataMap
    {
        $name = static::class;
        if (static::hasMap($name)) {
            return static::getMap($name);
        }
        Db::$LOG = false;

        // autogen table/view name from class
        $table = static::getDbTable();
        $view = static::getDbView();
        if (empty($view)) $view = $table;

        $v_meta = [];
        $t_meta = Db::getTableInfo($table);
        if (!empty($view)) {
            $v_meta = Db::getTableInfo($view);
        }

        Db::$LOG = true;

        $roCols = array_diff_key($v_meta, $t_meta);

        $map = new DataMap();

        // autogenerate a data map from DB and object metadata
        foreach ($t_meta+$roCols as $meta) {
            if (!property_exists($name, $meta->name_camel)) continue;
            $prop = new \ReflectionProperty(static::class, $meta->name_camel);

            /**
             * TODO: Looks like ReflectionType::getName() is deprecated
             *       The API here is odd! Will re-visit this code when PHP gets its
             *       reflection shit together.
             */
            //$typeName = (string)$prop->getType();
            /** @phpstan-ignore-next-line  */
            $typeName = $prop->getType()->getName();

            if ($typeName == Money::class) {
                $meta->php_type = $typeName;
            }

            $type = DataMap::makeDbType($meta);
            $type->setNullable($prop->getType()->allowsNull());

            if ($meta->is_primary_key) {
                $type->setFlag(DataMap::PRI);
            }

            if (
                $meta->Extra == 'VIRTUAL GENERATED' ||              // virtual field
                $prop->isReadOnly() ||                              // prop is readonly
                ($roCols[$meta->name] ?? false) ||                  // col not in table
                in_array($meta->name_camel, self::FORCE_READ_ONLY)  // tk system readonly props
            ) {
                $type->setAccess(DataMap::READ);
            }

            if ($type instanceof DateTime && $typeName == 'DateTimeImmutable') {
                $type->setImmutable(true);
            }

            $map->addType($type);
        }

        static::setMap($name, $map);
        return $map;
    }

    public static function getFormMap(): DataMap
    {
        $name = 'form_'. static::class;
        if (static::hasMap($name)) return static::getMap($name);

        Db::$LOG = false;

        $map = new DataMap();
        $primaryId = static::getDataMap()->getPrimaryKey()->getProperty();

        $reflect = new \ReflectionClass(static::class);
        $props = $reflect->getProperties(\ReflectionProperty::IS_PUBLIC | \ReflectionProperty::IS_PROTECTED);
        foreach ($props as $prop) {
            if (str_starts_with($prop->getName(), '_') || $prop->isStatic()) continue;

            /** TODO: see above comment */
            //$typeName = (string)$prop->getType();
            /** @phpstan-ignore-next-line  */
            $typeName = $prop->getType()->getName();

            $type = DataMap::makeFormType($typeName, $prop->getName());
            $type->setNullable($prop->getType()->allowsNull());

            if ($primaryId == $prop->getName()) {
                $type->setFlag(DataMap::PRI);
            }

            if (
                $prop->isReadOnly() ||
                in_array($prop->getName(), self::FORCE_READ_ONLY)
            ) {
                $type->setAccess(DataMap::READ);
            }

            $map->addType($type);
        }
        static::setMap($name, $map);

        Db::$LOG = true;

        return $map;
    }

    public static function getMap(string $name): ?DataMap
    {
        return self::$_MAPS[$name] ?? null;
    }

    public static function setMap(string $name, DataMap $map): void
    {
        self::$_MAPS[$name] = $map;
    }

    public static function hasMap(string $name): bool
    {
        return array_key_exists($name, self::$_MAPS);
    }

    public function getDataPath(): string
    {
        if (property_exists($this, 'dataPath')) {
            return $this->dataPath;
        }
        return Config::instance()->get('path.data', '/data');
    }

}